db.url=jdbc:postgresql://localhost:5433/studs
db.user=s502467
db.password=e6FdrAsXQC7RrJKv
hash.algorithm=SHA-1
read.executor=thread
process.executor=thread
send.executor=thread
sync.strategy=readwritelock
kafka.servers=localhost:9092